<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/crud/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.crud.'), function () {

Route::get('cruds', ['as'=> 'cruds.index', 'uses' => 'Crud\CrudController@index']);
Route::post('cruds', ['as'=> 'cruds.store', 'uses' => 'Crud\CrudController@store']);
Route::get('cruds/create', ['as'=> 'cruds.create', 'uses' => 'Crud\CrudController@create']);
Route::put('cruds/{cruds}', ['as'=> 'cruds.update', 'uses' => 'Crud\CrudController@update']);
Route::patch('cruds/{cruds}', ['as'=> 'cruds.update', 'uses' => 'Crud\CrudController@update']);
Route::get('cruds/{id}/delete', array('as' => 'cruds.delete', 'uses' => 'Crud\CrudController@getDelete'));
Route::get('cruds/{id}/confirm-delete', array('as' => 'cruds.confirm-delete', 'uses' => 'Crud\CrudController@getModalDelete'));
Route::get('cruds/{cruds}', ['as'=> 'cruds.show', 'uses' => 'Crud\CrudController@show']);
Route::get('cruds/{cruds}/edit', ['as'=> 'cruds.edit', 'uses' => 'Crud\CrudController@edit']);

});


Route::group(array('prefix' => 'admin/crud/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.crud.'), function () {

Route::get('cruds', ['as'=> 'cruds.index', 'uses' => 'Crud\CrudController@index']);
Route::post('cruds', ['as'=> 'cruds.store', 'uses' => 'Crud\CrudController@store']);
Route::get('cruds/create', ['as'=> 'cruds.create', 'uses' => 'Crud\CrudController@create']);
Route::put('cruds/{cruds}', ['as'=> 'cruds.update', 'uses' => 'Crud\CrudController@update']);
Route::patch('cruds/{cruds}', ['as'=> 'cruds.update', 'uses' => 'Crud\CrudController@update']);
Route::get('cruds/{id}/delete', array('as' => 'cruds.delete', 'uses' => 'Crud\CrudController@getDelete'));
Route::get('cruds/{id}/confirm-delete', array('as' => 'cruds.confirm-delete', 'uses' => 'Crud\CrudController@getModalDelete'));
Route::get('cruds/{cruds}', ['as'=> 'cruds.show', 'uses' => 'Crud\CrudController@show']);
Route::get('cruds/{cruds}/edit', ['as'=> 'cruds.edit', 'uses' => 'Crud\CrudController@edit']);

});
